// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:91151cfd-bac2-4677-ba9d-a51b2d6bf055",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_b17Lh9hPX",
    "aws_user_pools_web_client_id": "5u00p53l728033r7p9epqrslbo",
    "aws_user_files_s3_bucket": "ds-marketplace-images",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ukok3bszznaalbnadzu3tn2yym.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
